export const Cityname =  [
      "Karachi",
      "Lahore",
      "Islamabad",
      "Rawalpindi",
      "Peshawar",
      "Quetta",
      "Multan",
      "Faisalabad",
      "Gujranwala",
      "Sialkot",
      "Sargodha",
      "Bahawalpur",
      "Sukkur",
      "Hyderabad",
      "Abbottabad",
      "Rahim Yar Khan",
      "Mardan",
      "Sahiwal",
      "Dera Ghazi Khan",
      "Jhelum",
      "Muzaffarabad",
      "Mingora",
      "Charsadda",
      "Nawabshah",
      "Mirpur Khas",
      "Kotli",
      "Gujrat",
      "Okara",
      "Jacobabad",
      "Bannu",
      "Larkana",
      "Chiniot",
      "Kasur",
      "Turbat",
      "Khuzdar",
      "Attock",
      "Swat",
      "Hafizabad",
      "Pakpattan",
      "Dera Ismail Khan",
      "Narowal",
      "Shikarpur",
      "Jhang",
      "Kohat",
      "Tando Adam",
      "Dadu",
      "Mansehra",
      "Badin",
      "Ghotki",
      "Vehari",
      "Tando Allahyar",
      "Matiari",
      "Lodhran",
      "Hangu",
      "Tank",
      "Nowshera",
      "Hangu",
      "Mardan",
      "Zhob",
      "Chaman",
      "Gwadar",
      "Lasbela"
]